reference: "reference/GRCh38.fa"

threads:
  fastqc: 2
  bwa: 8
  samtools: 4
  trimmomatic: 4
  gatk: 4

trimmomatic:
  adapters: "/home/ndovie/miniconda3/envs/snakemake_env/share/trimmomatic/adapters/TruSeq3-PE.fa"
