# ============================================================
# DLBCL Tumor-Only WES Pipeline — Configuration
# ============================================================


# ------------------------------------------------------------
# Reference genome (GRCh38)
# ------------------------------------------------------------

reference: "reference/GRCh38.fa"

gene_uniprot_map: "reference/gene_uniprot_map.tsv"
canonical_ensp_map: "reference/ensembl_canonical_ensp.tsv"

# ------------------------------------------------------------
# Mutect2 resources
# ------------------------------------------------------------

# gnomAD germline resource
germline_resource: "reference/germline/af-only-gnomad.hg38.vcf.gz"

# Common variants for contamination estimation
common_variants: "reference/germline/small_exac_common_3.hg38.vcf.gz"

# Optional Panel of Normals
# Leave empty if not available
panel_of_normals: ""


# ------------------------------------------------------------
# Computational resources
# ------------------------------------------------------------

threads:
  fastqc: 2
  trimmomatic: 2
  bwa: 8
  gatk: 4
  vep: 4


# ------------------------------------------------------------
# Trimmomatic
# ------------------------------------------------------------

trimmomatic:
  adapters: "reference/adapters/NexteraPE-PE.fa"


# ------------------------------------------------------------
# VEP configuration
# ------------------------------------------------------------

# Directory ABOVE homo_sapiens/
# Contains:
# reference/homo_sapiens/115_GRCh38/

vep_cache: "reference"

vep_plugins_dir: "reference/vep_plugins"


# ------------------------------------------------------------
# VEP plugins
# ------------------------------------------------------------

vep_plugins:

  # CADD
  cadd_snv: "reference/CADD/whole_genome_SNVs.tsv.gz"

  # Uncomment only if you later download and prepare CADD indels
  # cadd_indels: "reference/CADD/InDels.tsv.gz"


  # REVEL
  revel: "reference/REVEL/revel_GRCh38.tsv.gz"


  # AlphaMissense
  alphamissense: "reference/AlphaMissense/AlphaMissense_hg38.tsv.gz"


  # ClinVar
  clinvar_vcf: "reference/clinvar/clinvar_GRCh38.vcf.gz"


# ------------------------------------------------------------
# Variant prioritization thresholds
# ------------------------------------------------------------

thresholds:

  # CADD PHRED score cutoff
  cadd_phred: 20

  # REVEL pathogenicity cutoff
  revel: 0.5

  # AlphaMissense classification threshold
  # (used later during prioritization)
  alphamissense_pathogenicity: 0.564

foldx_bin: "/head/NFS/dndovi/DLBCL_Analysis/tools/foldx_20261231"

# ------------------------------------------------------------
# DLBCL driver genes
# ------------------------------------------------------------

dlbcl_driver_genes:

  - KMT2D
  - TP53
  - BCL6
  - CREBBP
  - MYD88
  - CD79B
  - EZH2
  - PIM1
  - TNFRSF14
  - GNA13
  - B2M
  - CD58
  - SOCS1
  - TNFAIP3
  - BTG2
  - DTX1
  - MEF2B
  - PRDM1
  - STAT6
  - NOTCH1
  - NOTCH2
  - FOXO1
  - CCND3
  - TBL1XR1
  - BCL2
  - MYC
  - BCL7A
  - BACH2
  - IRF4
  - CIITA
  - CD74
  - PAX5
  - S1PR2
  - BIRC3
  - IRF8
  - CARD11
